-- MySQL Script generated by MySQL Workbench
-- Mon Sep  2 09:14:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Respostas_IFSP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Respostas_IFSP` ;

-- -----------------------------------------------------
-- Schema Respostas_IFSP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Respostas_IFSP` DEFAULT CHARACTER SET utf8 ;
USE `Respostas_IFSP` ;

-- -----------------------------------------------------
-- Table `Respostas_IFSP`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respostas_IFSP`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Respostas_IFSP`.`Usuario` (
  `Prontuario` INT NOT NULL,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(64) NOT NULL,
  `Tipo` ENUM('Aluno', 'Professor', 'Monitor') NOT NULL,
  PRIMARY KEY (`Prontuario`))
ENGINE = InnoDB;

INSERT INTO `Respostas_IFSP`.`Usuario` (`Prontuario`,`Nome`, `Email`,`Senha`, `Tipo`) VALUES ('1851021', 'Mariana Souza Santos', 'mariana.ms755@gmail.com', 'aabbccdd', 'Monitor');
INSERT INTO `Respostas_IFSP`.`Usuario` (`Prontuario`,`Nome`, `Email`,`Senha`, `Tipo`) VALUES ('1852841', 'Larissa Yumi Ohashi', 'lariyumi92@gmail.com', 'aabbccdd', 'Monitor');
INSERT INTO `Respostas_IFSP`.`Usuario` (`Prontuario`,`Nome`, `Email`,`Senha`, `Tipo`) VALUES ('1857461', 'Miguel Miranda', 'miguelmiranda2249@gmail.com', 'aabbccdd', 'Monitor');
INSERT INTO `Respostas_IFSP`.`Usuario` (`Prontuario`,`Nome`, `Email`,`Senha`, `Tipo`) VALUES ('1756731', 'Vitor Luis', 'vitorluispolo@gmail.com', 'aabbccdd', 'Monitor');

select * from `Respostas_IFSP`.`Usuario`;

-- -----------------------------------------------------
-- Table `Respostas_IFSP`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respostas_IFSP`.`Materia` ;

CREATE TABLE IF NOT EXISTS `Respostas_IFSP`.`Materia` (
  `Id` SMALLINT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (1, 'Matemática');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (2, 'Biologia');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (3, 'Geografia');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (4, 'História');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (5, 'Português');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (6, 'Física');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (7, 'Química');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (8, 'Sociologia');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (9, 'Inglês');
INSERT INTO `Respostas_IFSP`.`Materia` (`Id`, `Nome`) VALUES (10, 'Filosofia');

-- -----------------------------------------------------
-- Table `Respostas_IFSP`.`Duvida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respostas_IFSP`.`Duvida` ;

CREATE TABLE IF NOT EXISTS `Respostas_IFSP`.`Duvida` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Duvida` LONGTEXT NOT NULL,
  `Usuario_Prontuario` INT NOT NULL,
  `Materia_Id` SMALLINT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Dúvida_Usuario1_idx` (`Usuario_Prontuario` ASC) VISIBLE,
  INDEX `fk_Duvida_Materia1_idx` (`Materia_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Dúvida_Usuario1`
    FOREIGN KEY (`Usuario_Prontuario`)
    REFERENCES `Respostas_IFSP`.`Usuario` (`Prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Duvida_Materia1`
    FOREIGN KEY (`Materia_Id`)
    REFERENCES `Respostas_IFSP`.`Materia` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Respostas_IFSP`.`Prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respostas_IFSP`.`Prova` ;

CREATE TABLE IF NOT EXISTS `Respostas_IFSP`.`Prova` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Usuario_Prontuario` INT NOT NULL,
  `Materia_Id` SMALLINT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Prova_Usuario1_idx` (`Usuario_Prontuario` ASC) VISIBLE,
  INDEX `fk_Prova_Materia1_idx` (`Materia_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Prova_Usuario1`
    FOREIGN KEY (`Usuario_Prontuario`)
    REFERENCES `Respostas_IFSP`.`Usuario` (`Prontuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_Materia1`
    FOREIGN KEY (`Materia_Id`)
    REFERENCES `Respostas_IFSP`.`Materia` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Respostas_IFSP`.`Tema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Respostas_IFSP`.`Tema` ;

CREATE TABLE IF NOT EXISTS `Respostas_IFSP`.`Tema` (
  `Id` SMALLINT NOT NULL,
  `Tema` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

/*Matemática*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (1, 'Conjuntos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (2, 'Leis do seno e cosseno');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`)  VALUES (3, 'Funções afim e suas
 representações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (4, 'Sistemas de duas equações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (5, 'Equações e inequações
do 1º grau');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (6, ' Equações
do 2º grau');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (7, 'Inequação do 2º grau');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (8, 'Função quadrática e
 suas Representações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (9, ' Função Modular, Gráfico, Equações e Inequações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (10, 'Teorema de Pitágoras ');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (11, 'Função exponencial e
suas representações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (12, 'Função Logarítmica');

/*Biologia*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (13, 'Origem e formação dos
seres vivos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (14, 'Hipóteses sobre a origem da
vida e a vida primitiva');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (15, 'Ecossistema');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (16, 'Cadeia alimentar');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (17, 'Relações ecológicas');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (18, 'Ciclos biogeoquímicos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (19, 'Biomas');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (20, 'Ciclagem de Matéria e
Energia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (21, 'Química celular');

/*Geografia*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (22, 'Noções de cartografia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (23, 'Sistemas Naturais e Transformações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (24, 'Problemas ambientais do meio rural e dos centros urbanos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (25, 'Colapso do capitalismo estatal');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (26, 'Mundo multipolar');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (27, 'Noções de globalização');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (28, 'Urbanização');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (29, 'Relevos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (30, 'Climatologia');


/*História*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (31, 'Mundo Antigo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (32, 'Mundo Asiático');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (33, 'Mundo Grego');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (34, 'Mundo Romano');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (35, 'Mundo Medieval');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (36, 'Absolutismo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (37, 'Renascimento');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (38, 'Mercantilismo');

/*Português*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (39, 'Ortografia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (40, 'Descritivo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (41, 'Narrativo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (42, 'Dissertativo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (43, 'Trovadorismo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (44, 'Literatura Brasileira');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (45, 'Humanismo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (46, 'Escolas Literárias');

/*Física*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (47, 'Conceitos básicos da cinemática');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (48, 'Energia cinética, potencial e mecânica');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (49, 'Trabalho');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (50, 'Leis de Newton');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (51, 'Forças');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (52, 'Escalas Termométricas');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (53, 'Calorimetria');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (54, 'Matriz energética');

/*Química*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (55, 'Substâncias e Transformações');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (56, 'Processos de separação de mistura');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (57, 'Lei de Lavoisier');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (58, 'Lei de Proust');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (59, 'Modelos Atômicos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (60, 'Neutralização');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (61, 'Tabela Periódica');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (62, 'Ácidos, Bases, Sais e Óxidos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (63, 'Balanceamento');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (64, 'Mudanças de estados físicos');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (65, 'Camadas de valência');

/*Sociologia*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (66, 'Karl Marx');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (67, 'Mais-Valia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (68, 'Desigualdade social');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (69, 'Origem da Sociologia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (70, 'Raça e etnia');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (71, 'Capitalismo');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (72, 'Socialismo');

/*Inglês*/
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (73, 'Article');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (74, 'Adverb');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (75, 'Pronouns');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (76, 'Simple Present');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (77, 'Simple Past');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (78, 'Past Continuous');
INSERT INTO `Respostas_IFSP`.`Tema` (`Id`, `Tema`) VALUES (79, 'Verb to be');
